### ISSUE TITLE
docker 运行或许有问题

### ISSUE THREAD

**Issue by xioamingzxm** [yockii/xxqg-automate#10]
![image](https://user-images.githubusercontent.com/85006274/204271523-3d194044-ea56-469a-a860-b92ba530f5e5.png)
![image](https://user-images.githubusercontent.com/85006274/204271618-59549306-7021-4730-8247-d9ec819d029a.png)
docker运行命令如上，conf下的文件已正常映射到容器内部 配置完成后
修改 **服务器出口IP 与 消息接收地址**未成功
![image](https://user-images.githubusercontent.com/85006274/204271955-5e95599b-0e3d-407d-bfa9-bccc5e103ff8.png)
我确定我的服务器拥有公网IP 且可以被访问到

**Comment by yockii** [comment]
先确定一下是否能访问服务，直接浏览器访问你的访问  http://ip:8090/dingtalk  看看能否访问到 （出现Method Not Allowed即可）；判断是钉钉访问问题还是docker服务未启动的问题。
建议公网访问下，同时服务器上 curl 访问下都试试，确定问题所在。

**Comment by yockii** [comment]
另外，accessToken不需要前面的https部分，只要access_token=后面的部分

**Comment by yockii** [comment]
#11

**Comment by yockii** [comment]
#11
