### ISSUE TITLE
另外，accessToken不需要前面的https部分，只要access_token=后面的部分

### ISSUE THREAD

**Issue by xioamingzxm** [yockii/xxqg-automate#11]
另外，accessToken不需要前面的https部分，只要access_token=后面的部分

_Originally posted by @yockii in https://github.com/yockii/xxqg-automate/issues/10#issuecomment-1330027961_
     
1. 把配置文件放到指定/conf 映射目录
2.执行``` docker run --name xxag-server -p 8090:8080 -v /opt/conf:/conf -d yockii/xxqg_server ```命令
3.访问ip:8090/dingtalk无法访问

我在config.toml 内 [server] 下 写的是：port=8090 
是否配置文件的原因导致docker启动失败？

另：accessToken已更改 谢谢提醒

**Comment by yockii** [comment]
宿主机上是否能用curl访问 本地的8090端口（映射进docker内的）

2的命令好像有问题，你在配置文件中指定了port=8090，那么镜像内程序启动就会监听8090的端口，而执行的docker命令却是把8080映射出来用8090访问

把镜像启动的日志内容贴一下看看

**Comment by xioamingzxm** [comment]
> 
我重头运行了一次：
听了你的建议我将配置文件内设置如下：
![image](https://user-images.githubusercontent.com/85006274/204518542-c19cc7b8-5784-4219-8e8b-e128ed8bdc42.png)

并执行了命令：
[root@VM-16-8-centos conf]# docker run --name xxag-server -p 8080:8080 -v /opt/conf:/conf -d yockii/xxqg_server

curl执行情况：

**Comment by xioamingzxm** [comment]
> 宿主机上是否能用curl访问 本地的8090端口（映射进docker内的）
> 
> 2的命令好像有问题，你在配置文件中指定了port=8090，那么镜像内程序启动就会监听8090的端口，而执行的docker命令却是把8080映射出来用8090访问
> 
> 把镜像启动的日志内容贴一下看看





我重头运行了一次：
听了你的建议我将配置文件内设置如下：
![image](https://user-images.githubusercontent.com/85006274/204520246-1e12e08d-8b84-4b9f-a961-25e5142d6952.png)
并执行了命令：
[root@VM-16-8-centos conf]# docker run --name xxag-server -p 8080:8080 -v /opt/conf:/conf -d yockii/xxqg_server

curl执行情况：
![image](https://user-images.githubusercontent.com/85006274/204520394-a75541ee-f3e8-4d75-873f-2a7447f48ab3.png)
它们会卡住不动

以下为容器日志：
views: lstat ./views: no such file or directory
time="2022-11-29T11:36:04Z" level=debug msg="{\"expireIn\":7200,\"accessToken\":\"26949d31f60033258f88da037731a93d\"}" func=xxqg-automate/internal/job/wan.RefreshAccessToken file="/home/runner/work/xxqg-automate/xxqg-automate/internal/job/wan/AccessTokenJob.go:38"

**Comment by yockii** [comment]
检查是否有防火墙，本地用 curl http://localhost:8080 应该会返回 Cannot GET /

启动日志是正常的，并且获取到了钉钉的at了

**Comment by yockii** [comment]
还有钉钉那边配置如果没有证书，要禁用证书校验

**Comment by xioamingzxm** [comment]
> 要禁用证书校验

![image](https://user-images.githubusercontent.com/85006274/204704832-26cfcbe5-6b69-43db-a580-eae5957d177a.png)
应该是证书的原因 我该在哪里禁用ssl证书？

**Comment by xioamingzxm** [comment]
> 还有钉钉那边配置如果没有证书，要禁用证书校验
服务端和学习端配置信息如下：
![image](https://user-images.githubusercontent.com/85006274/204710760-762d6b13-5ab7-48a6-a0c3-31aef38d8ecb.png)
钉钉机器人已配置完成：
![image](https://user-images.githubusercontent.com/85006274/204710910-f4a5f8d4-daf6-4e7b-9052-fe82d93383d3.png)
学习端docker日志：
![image](https://user-images.githubusercontent.com/85006274/204711118-6f91b62f-d7a2-466d-bc7f-fddcc342dd99.png)
服务端日志：
![image](https://user-images.githubusercontent.com/85006274/204711187-c0944175-3f29-44f2-a475-6f1abbd80e96.png)
学习段创建时候的命令：
![image](https://user-images.githubusercontent.com/85006274/204711283-3c4552b7-c31d-4f6d-beef-01b92d7d7d39.png)
mysql数据库表如下：
![image](https://user-images.githubusercontent.com/85006274/204711474-bdf83915-df4c-438b-a37c-8497b8e0b589.png)
目前问题：
## 钉钉艾特群机器人无法得到回复
可能是mysql的原因？ 麻烦您再指导一下

**Comment by yockii** [comment]
日志如果没有报错mysql一般不会有问题，学习端由于需要先初始化浏览器首次启动可能会比较慢，这里也可以把 /tools 文件夹挂载到宿主机，下次可以不必再重新下载浏览器驱动。 客户端的配置文件中确保communicate.baseUrl 是正确指向你的服务端，如 http://xxxxxxx:8080    (不需要后面的部分)

**Comment by yockii** [comment]
t_user表再加个字段：

dingtalk_id  varchar(50)

**Comment by xioamingzxm** [comment]
> 
谢谢 终于完成了
