### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by twh808** [yockii/xxqg-automate#13]
报错日志stderr: exec /xxqg-agent: exec format error

**Comment by yockii** [comment]
有没有更多的信息，我本地测正常

**Comment by twh808** [comment]
没有了，一直报错这个，没有启动成功，我是蜚讯n1

**Comment by yockii** [comment]
docker启动还是直接程序启动？ docker是自带环境的呀

**Comment by yockii** [comment]
我查了你的这个蜚讯n1，是arm架构的cpu，应该是不兼容，docker中的程序是x86_64的amd64架构

**Comment by twh808** [comment]
好吧，老哥能支持一下arm64的吗

**Comment by yockii** [comment]
15版本增加了arm64的docker镜像，可以试试看

**Comment by twh808** [comment]
我试试

**Comment by twh808** [comment]
stderr: time="2022-12-02T08:50:33Z" level=warning msg="No config file: Config File \"config\" Not Found in \"[/conf]\" "
stderr: time="2022-12-02T08:50:33Z" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
stdout: views: lstat ./views: no such file or directory
报错

**Comment by yockii** [comment]
没有读取到配置文件，会用默认配置启动并生成数据库文件

**Comment by twh808** [comment]
能像study_xxqg一样打开网剧后台吗

**Comment by yockii** [comment]
没有做后台页面，是通过钉钉交互的。

**Comment by twh808** [comment]
好的👌
