### ISSUE TITLE
Win服务运行不了 提示错误如下

### ISSUE THREAD

**Issue by qiangguoyonghu** [yockii/xxqg-automate#15]
time="2023-01-01T14:30:37+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\deletesmile\\\\FileStorage\\\\File\\\\2023-01\\\\conf]\" "
time="2023-01-01T14:30:37+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.

time="2023-01-01T14:30:37+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\deletesmile\\\\FileStorage\\\\File\\\\2023-01\\\\conf]\" "
time="2023-01-01T14:30:37+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.

time="2023-01-01T14:30:37+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\deletesmile\\\\FileStorage\\\\File\\\\2023-01\\\\conf]\" "
time="2023-01-01T14:30:37+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.

time="2023-01-01T14:30:37+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\deletesmile\\\\FileStorage\\\\File\\\\2023-01\\\\conf]\" "
time="2023-01-01T14:30:37+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.

time="2023-01-01T14:30:37+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\deletesmile\\\\FileStorage\\\\File\\\\2023-01\\\\conf]\" "
time="2023-01-01T14:30:37+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.

time="2023-01

**Comment by yockii** [comment]
没有有效信息，建议命令行中启动看输出内容

**Comment by qiangguoyonghu** [comment]
单机版的提示C:\Users\Administrator>D:\xxqg-agent_1.0.16_Windows_x86_64.exe
time="2023-01-02T21:54:42+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\conf]\" "
time="2023-01-02T21:54:42+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.
2023/01/02 21:54:42 /home/runner/go/pkg/mod/github.com/yockii/qscore@v0.0.0-20221201054601-20f54d279ce0/pkg/database/Index.go:57: ->NewDBDao创建dataSource失败:->newDataSource-->DSN cannot be empty
time="2023-01-02T21:54:42+08:00" level=error msg="数据库创建失败!  ->NewDBDao创建dataSource失败:->newDataSource-->DSN cannot be empty" func=github.com/yockii/qscore/pkg/database.initSqlite file="/home/runner/go/pkg/mod/github.com/yockii/qscore@v0.0.0-20221201054601-20f54d279ce0/pkg/database/Index.go:69" caller=
time="2023-01-02T21:54:48+08:00" level=error msg="Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\conf]\"" func=main.init.0 file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:51" caller=
time="2023-01-02T21:54:48+08:00" level=info msg="当前应用版本: v1.0.16" func=main.main file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:63"
time="2023-01-02T21:54:48+08:00" level=info msg="开始检测环境....." func=main.main file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:64"
2023/01/02 21:54:51 /home/runner/go/pkg/mod/github.com/yockii/qscore@v0.0.0-20221201054601-20f54d279ce0/pkg/database/Index.go:63: ->newDataSource-->ping数据库失败:unable to open database file: out of memory (14)
2023/01/02 21:54:51 /home/runner/go/pkg/mod/github.com/yockii/qscore@v0.0.0-20221201054601-20f54d279ce0/pkg/database/Index.go:47: ->NewDBDao创建dataSource失败:->newDataSource-->ping数据库失败:unable to open database file: out of memory (14)
time="2023-01-02T21:54:51+08:00" level=error msg="数据库创建失败!  ->NewDBDao创建dataSource失败:->newDataSource-->ping数据库失败:unable to open database file: out of memory (14)" func=github.com/yock

**Comment by qiangguoyonghu** [comment]
服务版提示Microsoft Windows [版本 10.0.22000.978]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Administrator>"D:\xxqg-server_1.0.16_Windows_x86_64 2.exe"
time="2023-01-02T21:59:54+08:00" level=warning msg="No config file: Config File \"config\" Not Found in \"[C:\\\\Users\\\\Administrator\\\\conf]\" "
time="2023-01-02T21:59:54+08:00" level=warning msg="设置日志级别失败: not a valid logrus Level: \"\", 将使用默认[info]级别"
views: CreateFile ./views: The system cannot find the file specified.

**Comment by yockii** [comment]
有没有根据说明，配置conf文件夹？agent端放入db数据库？

**Comment by yockii** [comment]
如有问题再开issue，关闭当前issue
