### ISSUE TITLE
win 服务端运行错误

### ISSUE THREAD

**Issue by donqee** [yockii/xxqg-automate#16]
原来运行在linux环境，后来换了win,死活运行不了。
提示路径问题，加载不了配置文件，肯定的是配置文件和路径没有任何问题
time="2023-02-2GT1G:51:02+08:G level=warning msg="No"config>" Not Found in  "[C: \\conf ] "logrus Level:""，将使用默认[info]级别"lews:
config file:
Config File
time="2023-02-20T10:51:@2+08:”level=warning msg="设置日志级别失败: not a vali
CreateFile ./views: The system cannot find the file specified.

**Comment by donqee** [comment]
![运行错误](https://user-images.githubusercontent.com/10410304/219999035-2c7f7f2c-aa95-4766-9e8c-84f39794dec2.jpg)

**Comment by donqee** [comment]
![报错图片2](https://user-images.githubusercontent.com/10410304/220000374-79f1b2e8-da46-4a3a-bec2-02b3832425b1.jpg)

**Comment by yockii** [comment]
后缀是否正确，因为我看我的windows下，config.toml，显示的类型应为 TOML文件，而不是文本文档。

**Comment by yockii** [comment]
![image](https://user-images.githubusercontent.com/5021467/220036598-2d1ae059-e030-41e2-8a20-50eef5995d4f.png)

![image](https://user-images.githubusercontent.com/5021467/220036654-09e356dd-a20b-4934-9d82-67d0e4697ed6.png)

**Comment by donqee** [comment]
![新错误](https://user-images.githubusercontent.com/10410304/220073678-e931d1e9-7eb8-436e-aaed-ecc22e556957.png)

果然是后缀名字的原因，犯的错误好低级，哈哈
又开始报这个错了。

**Comment by yockii** [comment]
这是钉钉返回的消息，检查你是否配置了钉钉的相关信息
