### ISSUE TITLE
此页面因为 SSL证书异常导致访问失败，请联系管理员或者服务提供商处理。

### ISSUE THREAD

**Issue by donqee** [yockii/xxqg-automate#17]
![微信图片_20230223153107](https://user-images.githubusercontent.com/10410304/220843914-ba1de955-ab90-46e9-86c6-aebbbc3c606e.jpg)

**Comment by yockii** [comment]
这个应该是苹果手机出现的问题，可以把该页面用浏览器打开后保存后，放入自己的服务器上（静态页面，可以访问即可）
页面地址就是配置文件中 xxqg.schema的地址

**Comment by yockii** [comment]
> ![微信图片_20230223153107](https://user-images.githubusercontent.com/10410304/220843914-ba1de955-ab90-46e9-86c6-aebbbc3c606e.jpg)

我已经在wiki中加入了如何访问自己的中转页面

**Comment by yockii** [comment]
如有问题再开issue
