### ISSUE TITLE
大佬 能不能给个简单一点教程

### ISSUE THREAD

**Issue by Orzyiii** [yockii/xxqg-automate#18]
我把文档来来回回搞了好几遍 
所有版本  都弄成功
求大佬 给个简单易懂的教程
![image](https://user-images.githubusercontent.com/86647919/236431421-77b29a27-ef20-4790-8979-f0f8427f3dc3.png)

**Comment by yockii** [comment]
基本都是成功的，只是与服务器通信部分的配置错误，如果单机运行可以无视，如果是需要服务器接入钉钉，则把对应的http://server-host:port 配置为对应的服务器地址和端口信息就可以了。

**Comment by yockii** [comment]
主要原则就是两个端，服务端负责钉钉接入，学习端（你截图的）负责实际学习。有任何具体问题随时留言，有时候自己鼓捣半天，可能问一下几分钟就解决了。

**Comment by coward0720** [comment]
大佬，我想学习端单机运行，请问如何操作呢？

**Comment by coward0720** [comment]
> 主要原则就是两个端，服务端负责钉钉接入，学习端（你截图的）负责实际学习。有任何具体问题随时留言，有时候自己鼓捣半天，可能问一下几分钟就解决了。

大佬，我想学习端单机运行，请问如何操作呢？

**Comment by yockii** [comment]
> > 主要原则就是两个端，服务端负责钉钉接入，学习端（你截图的）负责实际学习。有任何具体问题随时留言，有时候自己鼓捣半天，可能问一下几分钟就解决了。
> 
> 大佬，我想学习端单机运行，请问如何操作呢？

agent独立运行的话，参考 https://github.com/yockii/xxqg-automate/wiki/%E7%8B%AC%E7%AB%8Bagent%E8%BF%90%E8%A1%8C%E8%AF%B4%E6%98%8E

独立运行是暴露接口的，根据你在conf/config.toml文件中配置的端口号，后面加上接口即可。

注意 重定向登录链接需要在有安装app的手机上访问

**Comment by yockii** [comment]
> 我把文档来来回回搞了好几遍 所有版本 都弄成功 求大佬 给个简单易懂的教程 ![image](https://user-images.githubusercontent.com/86647919/236431421-77b29a27-ef20-4790-8979-f0f8427f3dc3.png)

https://github.com/yockii/xxqg-automate/wiki/%E7%8B%AC%E7%AB%8Bagent%E8%BF%90%E8%A1%8C%E8%AF%B4%E6%98%8E
更新了独立启动，最简单的方式完成运行
