### ISSUE TITLE
NewDBDao创建dataSource失败  queryContext查询rows错误:SQL logic error: no such column: only_login_tag (1)

### ISSUE THREAD

**Issue by fvlw** [yockii/xxqg-automate#19]
![图片](https://github.com/yockii/xxqg-automate/assets/71577616/27c726e8-6cd1-49ba-982a-b36c51492a4d)

![图片](https://github.com/yockii/xxqg-automate/assets/71577616/88ded0da-47a6-4aba-a0a9-91d16be1751c)
可以获取到用户信息但是显示wrapExecUpdateValuesAffected执行保存错误:SQL logic error: table t_user has no column named only_login_tag (1)

**Comment by yockii** [comment]
嗯，这个是我疏忽了，增加了标识字段却忘记在启动时自动尝试去执行添加字段的语句了。已更新，重新下载23版本再尝试一下。谢谢指正！
