### ISSUE TITLE
未获取到data.taskProgress:  未成功获取用户积分信息 获取积分异常!

### ISSUE THREAD

**Issue by fvlw** [yockii/xxqg-automate#20]
![图片](https://github.com/yockii/xxqg-automate/assets/71577616/ffd254bc-c8c6-4836-8b47-22ab4a5b2bdc)

**Comment by yockii** [comment]
收到，这是因为原来可以直接获取分数的接口被关闭了导致的。代码中原先保留了接口获取的方式，但会优先通过模拟网页的方式读取，网页中读取不到再尝试接口获取。一会更新版本将接口方式去掉。

**Comment by fvlw** [comment]
![图片](https://github.com/yockii/xxqg-automate/assets/71577616/58be3966-5d3f-4899-b70a-9f7d114dac2d)

![图片](https://github.com/yockii/xxqg-automate/assets/71577616/58f5e0d2-91da-44a8-8b41-1ba6245d362c)

刷分没效果 
![图片](https://github.com/yockii/xxqg-automate/assets/71577616/0d66cf85-ccce-4b66-921f-03e26f0f8d3b)

获取账号是1 是正常的

**Comment by yockii** [comment]
看lastStudyTime，在当前时间之前表示上次学习时间，之后表示本次真正学习开始时间。

因为agent是允许同时有多个账号学习的，所以为了避免这些账号都集中在同一时间点学习，会自动进行随机延迟，到了延迟时间才会真正开始学习
