### ISSUE TITLE
这个样子以后怎么登陆呀

### ISSUE THREAD

**Issue by www338** [yockii/xxqg-automate#21]
views: CreateFile ./views: The system cannot find the file specified.
failed to rotate: failed to create new symlink: symlink C:\Users\wy197\Desktop\xx1\logs\info-2023-05-13.log C:\Users\wy197\Desktop\xx1\logs/info-2023-05-13.log_symlink: A required privilege is not held by the client.
time="2023-05-13T10:46:12+08:00" level=info msg="当前应用版本: v1.0.23" func=main.main file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:63"
time="2023-05-13T10:46:12+08:00" level=info msg="开始检测环境....." func=main.main file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:64"
2023/05/13 10:46:12 /home/runner/go/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/run.go:107: Downloading driver to C:\Users\wy197\Desktop\xx1\tools\driver\ms-playwright-go\1.20.0-beta-1647057403000
2023/05/13 10:46:22 /home/runner/go/pkg/mod/github.com/playwright-community/playwright-go@v0.2000.1/run.go:160: Downloaded driver successfully
2023/05/13 10:46:23 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_job WHERE status=2 ,args: [] ,execSQLMillis: 0
2023/05/13 10:46:23 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:1120: sql:  create table t_user
(
    id               varchar(50)
        constraint t_user_pk
            primary key,
    nick             varchar(50),
    uid              varchar(50),
    token            varchar(500),
    login_time       INTEGER,
    status           INTEGER,
    create_time      datetime,
    last_check_time  datetime,
    last_study_time  datetime,
    last_finish_time datetime,
    last_score       INTEGER,
    score            INTEGER,
    only_login_tag       INTEGER,
    dingtalk_id      varchar(50)
); ,args: [] ,execSQLMillis: 0
2023/05/13 10:46:23 /home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:154: ->UpdateFinder-->wrapExecUpdateValuesAffected执行更新错误:SQL logic error: table t_user already exists (1)
2023/05/13 10:46:23 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:1120: sql:  create table t_job
(
    id          varchar(50)
        constraint t_job_pk
            primary key,
    user_id     varchar(50),
    score       INTEGER,
    status      INTEGER,
    code        varchar(50),
    create_time datetime
); ,args: [] ,execSQLMillis: 0
2023/05/13 10:46:23 /home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:166: ->UpdateFinder-->wrapExecUpdateValuesAffected执行更新错误:SQL logic error: table t_job already exists (1)
2023/05/13 10:46:23 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:1120: sql:  alter table t_user add column only_login_tag INTEGER; ,args: [] ,execSQLMillis: 0
2023/05/13 10:46:23 /home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:169: ->UpdateFinder-->wrapExecUpdateValuesAffected执行更新错误:SQL logic error: duplicate column name: only_login_tag (1)
2023/05/13 10:46:23 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_job WHERE status=1 ,args: [] ,execSQLMillis: 0
time="2023-05-13T10:46:23+08:00" level=info msg="正在检查更新." func=xxqg-automate/internal/update.CheckUpdate file="/home/runner/work/xxqg-automate/xxqg-automate/internal/update/index.go:103"
time="2023-05-13T10:46:23+08:00" level=info msg="检查更新完成. 当前已运行最新版本." func=xxqg-automate/internal/update.CheckUpdate file="/home/runner/work/xxqg-automate/xxqg-automate/internal/update/index.go:127"
2023/05/13 10:48:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2023-05-13 06:48:00.0021994 +0800 CST m=-14292.488749599] ,execSQLMillis: 0
2023/05/13 10:48:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_study_time is null or last_study_time<?) and status>0 and only_login_tag <> 1 ,args: [2023-05-12 14:48:00.0023987 +0800 CST m=-71892.488550299] ,execSQLMillis: 0
2023/05/13 10:48:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE last_study_time>? and last_study_time<? and (last_finish_time is null or last_finish_time<last_study_time or last_score<10) and status>0 and only_login_tag <> 1 ,args: [2023-05-13 2023-05-13 09:48:00.003527 +0800 CST m=-3492.487421699] ,execSQLMillis: 0

**Comment by yockii** [comment]
如果是直接启动agent端，那么就浏览器打开部署端位置的API（如 http://localhost:8080/api/v1/redirectXxqg)

接口信息参考https://github.com/yockii/xxqg-automate/wiki/%E7%8B%AC%E7%AB%8Bagent%E8%BF%90%E8%A1%8C%E8%AF%B4%E6%98%8E
