### ISSUE TITLE
server端linux amd64无法运行

### ISSUE THREAD

**Issue by river0Love** [yockii/xxqg-automate#3]
使用CentOS Linux release 7.6.1810 (Core)系统
添加运行权限后
 ./xxqg_server 
-bash: ./xxqg_server: cannot execute binary file

此外能否添加任务端linux amd64版本
 I’m truly grateful for your help

**Comment by yockii** [comment]
好的，我把几个主要架构都编译一下你再试试

**Comment by yockii** [comment]
> 使用CentOS Linux release 7.6.1810 (Core)系统 添加运行权限后 ./xxqg_server -bash: ./xxqg_server: cannot execute binary file
> 
> 此外能否添加任务端linux amd64版本 I’m truly grateful for your help

新编译后的文件试试能否执行

**Comment by river0Love** [comment]
### log
**server:**
`./xxqg-server_1.0.8_Linux_x86_64 
views: lstat ./views: no such file or directory
DEBU[0000]/home/runner/work/xxqg-automate/xxqg-automate/internal/job/wan/AccessTokenJob.go:38 xxqg-automate/internal/job/wan.RefreshAccessToken() {"expireIn":7200,"accessToken":"223d0702ac6e336a8c0e788b1c4fad90"}
`
**agent:**
`time="2022-11-09 21:04:53" level=info msg="当前应用版本: 1.0.8" func=main.main file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:38"
time="2022-11-09 21:04:53" level=info msg="开始检测环境....." func=main.main file="/home/runner/work/xxqg-automate/xxqg-automate/cmd/lan/main.go:39"
time="2022-11-09 21:04:54" level=info msg="正在检查更新." func=xxqg-automate/internal/update.CheckUpdate file="/home/runner/work/xxqg-automate/xxqg-automate/internal/update/index.go:103"
time="2022-11-09 21:04:54" level=info msg="db_sha: d6e455f03b419af108cced07ea1d17f8268400ad1b6d80cb75d58e952a5609bf" func=xxqg-automate/internal/util.CheckQuestionDB file="/home/runner/work/xxqg-automate/xxqg-automate/internal/util/QuestionBank.go:43"
`
**config**   ：
server端填写完[server]  [dingtalk]  [logger]
agent端填写完[database]  [logger]  [xxqg]   [communicate]
钉钉无任何提示出现
此时我不知如何在钉钉进行下一步操作

**Comment by yockii** [comment]
> 

在钉钉中@机器人，发送  登录，可以获取登录连接；发送  统计，可以获取学习统计信息

**Comment by yockii** [comment]
> Author

我添加了[交互操作说明](https://github.com/yockii/xxqg-automate/wiki/%E9%92%89%E9%92%89%E4%BA%A4%E4%BA%92%E8%AF%B4%E6%98%8E)

**Comment by river0Love** [comment]
我仔细阅读后并未发现开始学习指令

**Comment by river0Love** [comment]
统计显示学习中分数实则未增加

**Comment by yockii** [comment]
开始学习是自动的，会在之后的2小时内随机一个时间开始学习。次日提前4小时开始随机，但最早不早于6点

**Comment by yockii** [comment]
观察学习的程序是否有报错异常

**Comment by river0Love** [comment]
time="2022-11-10 21:06:33" level=warning msg="版本格式错误" func=xxqg-automate/internal/update.CheckUpdate file="/home/runner/work/xxqg-automate/xxqg-automate/internal/update/index.go:114"
请问此问题是否影响

**Comment by yockii** [comment]
> 

并无影响

**Comment by yockii** [comment]
学习中有可能你的学习时间还未到。学习中的意思实际上是指，已经生成学习任务了，一直到学习结束的状态。
生成学习任务前，是等待学习

**Comment by river0Love** [comment]
ERRO[0007] [core]  初始化chrome失败                           source="core.go:182"
ERRO[0007] [core]  could not send message: could not send message to server: 
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     npx playwright install-deps                            ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝  source="core.go:183"
抱歉没有及时回复，请问linux报此错如何解决

**Comment by yockii** [comment]
> ║ npx playwright install-deps ║

嗯，这个问题可能需要playwright那边看看怎么处理了。
从这个错误上看，是系统缺少一些启动浏览器的依赖。可以移步 https://github.com/playwright-community/playwright-go 看看。

贴下几个命令看看是否能够解决：

go install github.com/playwright-community/playwright-go/cmd/playwright
playwright install --with-deps

**Comment by yockii** [comment]
可能需要先尝试安装golang环境：
```
yum install -y golang
```
然后进行安装依赖：
```
go install github.com/playwright-community/playwright-go/cmd/playwright@latest
playwright install --with-deps
```

**Comment by yockii** [comment]
> ERRO[0007] [core] could not send message: could not send message to server:

我在Ubuntu 20的环境中测试可以使用，redhat系列的可能会有点问题，建议使用ubuntu环境
