### ISSUE TITLE
提供下详细的部署方法吧

### ISSUE THREAD

**Issue by donqee** [yockii/xxqg-automate#4]
对小白来说不太友好

**Comment by yockii** [comment]
我抽空再更新下wiki内容吧。不知道是哪点不明白，我针对性地详细说明一下

**Comment by donqee** [comment]
> 

部署的步骤越详细越好哈

**Comment by yockii** [comment]
> > 
> 
> 部署的步骤越详细越好哈

已经做了大量补充了，点击wiki中查看。主要是准备步骤。实际运行，只要配置文件有了，直接运行即可
