### ISSUE TITLE
真的很好用，省心省事部署方便，可以设置定时学习吗？

### ISSUE THREAD

**Issue by donqee** [yockii/xxqg-automate#6]
可以设置定时学习或者是@钉钉机器人 主动学习吗？

**Comment by yockii** [comment]
目前的规则是前一日学习时间-4小时 开始，不早于6点开始执行任务，执行任务时，会进行随机延迟0-120分钟，避免多人同时学习。

**Comment by yockii** [comment]
主动学习我考虑下怎么加入
