### ISSUE TITLE
1.09服务端报错

### ISSUE THREAD

**Issue by donqee** [yockii/xxqg-automate#7]
ERRO[0038]/home/runner/go/pkg/mod/github.com/yockii/qscore@v0.0.0-20221107040215-7ca57c896227/pkg/server/Index.go:50 github.com/yockii/qscore/pkg/server.InitWebApp.func1() runtime error: index out of range [0] with length 0  caller=

**Comment by yockii** [comment]
已修复，重新下载

**Comment by donqee** [comment]
> 已修复，重新下载

可以了，我看你增了钉钉的学习，如何立即学习？或者是制定用户学习？ 没有新的交互命令吗

**Comment by yockii** [comment]
> > 已修复，重新下载
> 
> 可以了，我看你增了钉钉的学习，如何立即学习？或者是制定用户学习？ 没有新的交互命令吗

在登录的时候，自动绑定登录用户的钉钉信息，然后这个用户主动@机器人，发送内容带”学习“就会立即执行学习【最近条件受限，未能进行实测】
