### ISSUE TITLE
有docker版本吗？

### ISSUE THREAD

**Issue by zjdaxue** [yockii/xxqg-automate#8]
有docker版本吗？

**Comment by zjdaxue** [comment]
windows版本怎么使用，能不教程吗

**Comment by yockii** [comment]
> windows版本怎么使用，能不教程吗

windows版本使用起来是一样的，docker版本暂时还没有弄，等有时间我看看

**Comment by yockii** [comment]
> 有docker版本吗？

已添加，不过没有时间做测试，你可以参考用用看。

**Comment by donqee** [comment]
> > 有docker版本吗？
> 
> 已添加，不过没有时间做测试，你可以参考用用看。

给开发者点赞，真厉害，响应速度也快，膜拜
