### ISSUE TITLE
客户端报错

### ISSUE THREAD

**Issue by donqee** [yockii/xxqg-automate#9]
time="2022-11-22T10:04:55+08:00" level=error msg="积分获取失败，停止答题 <nil>" func="xxqg-automate/internal/study.(*core).Answer" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/Answer.go:47" caller=
time="2022-11-22T10:04:56+08:00" level=error msg="积分获取失败，停止答题 <nil>" func="xxqg-automate/internal/study.(*core).Answer" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/Answer.go:47" caller=
time="2022-11-22T10:04:56+08:00" level=error msg="积分获取失败，停止答题 <nil>" func="xxqg-automate/internal/study.(*core).Answer" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/Answer.go:47" caller=
2022/11/22 10:05:01 /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884: ->Transaction-->recover异常:runtime error: invalid memory address or nil pointer dereference
time="2022-11-22T10:05:01+08:00" level=error msg="->Transaction-->recover异常:runtime error: invalid memory address or nil pointer dereference" func="xxqg-automate/internal/study.(*StudyingJob).startStudy" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/core.go:281" caller=
2022/11/22 10:06:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2022-11-22 06:06:00.0098231 +0800 CST m=-14304.712917999] ,execSQLMillis: 0
2022/11/22 10:06:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_study_time is null or last_study_time<?) and status>0 ,args: [2022-11-21 14:06:00.0098231 +0800 CST m=-71904.712917999] ,execSQLMillis: 0
2022/11/22 10:06:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE last_study_time>? and last_study_time<? and (last_finish_time is null or last_finish_time<last_study_time) and status>0 ,args: [2022-11-22 2022-11-22 09:06:00.0166078 +0800 CST m=-3504.706133299] ,execSQLMillis: 0
2022/11/22 10:08:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2022-11-22 06:08:00.0134004 +0800 CST m=-14184.709340699] ,execSQLMillis: 0
2022/11/22 10:09:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_study_time is null or last_study_time<?) and status>0 ,args: [2022-11-21 14:09:00.0074525 +0800 CST m=-71724.715288599] ,execSQLMillis: 0
2022/11/22 10:09:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE last_study_time>? and last_study_time<? and (last_finish_time is null or last_finish_time<last_study_time) and status>0 ,args: [2022-11-22 2022-11-22 09:09:00.0080957 +0800 CST m=-3324.714645399] ,execSQLMillis: 0
2022/11/22 10:10:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2022-11-22 06:10:00.0074625 +0800 CST m=-14064.715278599] ,execSQLMillis: 0

xxqg-agent_1.0.10_Windows_x86_64.exe

**Comment by donqee** [comment]
钉钉机器人无法登录，1.0.10一样存在这样的问题，无法登录

**Comment by yockii** [comment]
> 钉钉机器人无法登录，1.0.10一样存在这样的问题，无法登录

数据库需要增加dingtalk_id的字段，或者直接下载代码中 conf/data.db 的空文件覆盖

**Comment by yockii** [comment]
> time="2022-11-22T10:04:55+08:00" level=error msg="积分获取失败，停止答题 " func="xxqg-automate/internal/study.(*core).Answer" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/Answer.go:47" caller= time="2022-11-22T10:04:56+08:00" level=error msg="积分获取失败，停止答题 " func="xxqg-automate/internal/study.(*core).Answer" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/Answer.go:47" caller= time="2022-11-22T10:04:56+08:00" level=error msg="积分获取失败，停止答题 " func="xxqg-automate/internal/study.(*core).Answer" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/Answer.go:47" caller= 2022/11/22 10:05:01 /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884: ->Transaction-->recover异常:runtime error: invalid memory address or nil pointer dereference time="2022-11-22T10:05:01+08:00" level=error msg="->Transaction-->recover异常:runtime error: invalid memory address or nil pointer dereference" func="xxqg-automate/internal/study.(*StudyingJob).startStudy" file="/home/runner/work/xxqg-automate/xxqg-automate/internal/study/core.go:281" caller= 2022/11/22 10:06:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2022-11-22 06:06:00.0098231 +0800 CST m=-14304.712917999] ,execSQLMillis: 0 2022/11/22 10:06:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_study_time is null or last_study_time<?) and status>0 ,args: [2022-11-21 14:06:00.0098231 +0800 CST m=-71904.712917999] ,execSQLMillis: 0 2022/11/22 10:06:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE last_study_time>? and last_study_time<? and (last_finish_time is null or last_finish_time<last_study_time) and status>0 ,args: [2022-11-22 2022-11-22 09:06:00.0166078 +0800 CST m=-3504.706133299] ,execSQLMillis: 0 2022/11/22 10:08:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2022-11-22 06:08:00.0134004 +0800 CST m=-14184.709340699] ,execSQLMillis: 0 2022/11/22 10:09:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_study_time is null or last_study_time<?) and status>0 ,args: [2022-11-21 14:09:00.0074525 +0800 CST m=-71724.715288599] ,execSQLMillis: 0 2022/11/22 10:09:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE last_study_time>? and last_study_time<? and (last_finish_time is null or last_finish_time<last_study_time) and status>0 ,args: [2022-11-22 2022-11-22 09:09:00.0080957 +0800 CST m=-3324.714645399] ,execSQLMillis: 0 2022/11/22 10:10:00 /home/runner/go/pkg/mod/gitee.com/chunanyong/zorm@v1.6.3/DBDao.go:627: sql: SELECT * FROM t_user WHERE (last_check_time is null or last_check_time<?) and status>0 ,args: [2022-11-22 06:10:00.0074625 +0800 CST m=-14064.715278599] ,execSQLMillis: 0
> 
> xxqg-agent_1.0.10_Windows_x86_64.exe

该问题可能是过期导致积分获取失败，更新数据时的异常，11版本进行修复
